<style type="text/css">
<!--
* {
    box-sizing: border-box;
}

table {
    border-collapse: collapse;
}

.block {
    position: relative;
    width: 100%;
}

.block .line {
    height: 2px;
    border-bottom: solid 1px black;
}

.block .sol, .block .fa {
    position: absolute;
    height: 100px;
    background-repeat: no-repeat;
}

.block .sol {
    background-image: url(sol.png);
}

.block .fa {
    background-image: url(fa.png);
    margin-top: 200px;
}
-->
</style>
<page style="font-size: 14px">

    <div id="header" style="margin-top: 50px"></div>

    <div class="block">
        <div class="sol">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
        <div class="fa">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
    </div>
</page>